In [2]:
import numpy as np
import warnings as wp

In [25]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10]) #Creating a array
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr1 = np.arange(0,20,2) #Creating a array example 2
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.repeat(10,5) #create a array that repeats
np.zeros((3)) #Create a array of zeros

array([0., 0., 0.])

In [24]:
np.random.random(4) #Creating a random array
random_array = np.random.randint(0, 100, 10) #Creating a random array of desired range

array([75, 34,  3, 54, 78, 43, 35,  5, 35, 24])

In [36]:
arr1 = np.array([12,28,99,31,17,4,1,77])


In [38]:
ar = np.arange(1,20)
rep1 = np.where( ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [45]:
#Array Mathematics
arr1 = np.arange(1,20)
arr2 = np.arange(20,39)
np.add(arr1,arr2) #adding two arrays
np.subtract(arr1,arr2) #subtraction
np.divide(arr1,arr2) #dividng
np.multiply(arr1,arr2) #multiply
np.exp(arr1) #exponentiation
np.sqrt(arr1) #square root
np.sin(arr1) #sinus
np.log(arr1) #natural logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [52]:
arr1 = np.random.randint(1,100,10)
arr1.sort()
arr1.sum()
arr1.min()
arr1.max()
arr1.mean()
arr2 = np.copy(arr2) # copying array

36.4